using System;
namespace PFE.Models
{
    public class ARTFAMILLES_CPT
    {
        public int? ARFID { get; set; }
        public string ARFCLASS { get; set; }
        public int? CPTID_FR { get; set; }
        public int? CPTID_EX { get; set; }
        public int? CPTID_CE { get; set; }
        public int? CPTID_CT { get; set; }
        public int? CPTID_DV { get; set; }
        public int? CPTID_DV1 { get; set; }
        public int? CPTID_DV2 { get; set; }
        public int? CPTID_DV3 { get; set; }
        public int? CPTID_DV4 { get; set; }
        public int? CPTID_DV5 { get; set; }
        public int? ANSID_FR { get; set; }
        public int? ANSID_EX { get; set; }
        public int? ANSID_CE { get; set; }
        public int? ANSID_CT { get; set; }
        public int? ANSID_DV { get; set; }
        public int? ANSID_DV1 { get; set; }
        public int? ANSID_DV2 { get; set; }
        public int? ANSID_DV3 { get; set; }
        public int? ANSID_DV4 { get; set; }
        public int? ANSID_DV5 { get; set; }
        public int? TVACODE_FR { get; set; }
        public int? TVACODE_EX { get; set; }
        public int? TVACODE_CE { get; set; }
        public int? TVACODE_CT { get; set; }
        public int? TVACODE_DV { get; set; }
        public int? TVACODE_DV1 { get; set; }
        public int? TVACODE_DV2 { get; set; }
        public int? TVACODE_DV3 { get; set; }
        public int? TVACODE_DV4 { get; set; }
        public int? TVACODE_DV5 { get; set; }
        public int? TPFCODE_FR { get; set; }
        public int? TPFCODE1_FR { get; set; }
        public int? TPFCODE2_FR { get; set; }
        public int? TPFCODE3_FR { get; set; }
        public int? TPFCODE4_FR { get; set; }
        public int? TPFCODE5_FR { get; set; }
        public int? TPFCODE6_FR { get; set; }
        public int? TPFCODE7_FR { get; set; }
        public int? TPFCODE8_FR { get; set; }
        public int? TPFCODE9_FR { get; set; }
        public int? TPFCODE_EX { get; set; }
        public int? TPFCODE1_EX { get; set; }
        public int? TPFCODE2_EX { get; set; }
        public int? TPFCODE3_EX { get; set; }
        public int? TPFCODE4_EX { get; set; }
        public int? TPFCODE5_EX { get; set; }
        public int? TPFCODE6_EX { get; set; }
        public int? TPFCODE7_EX { get; set; }
        public int? TPFCODE8_EX { get; set; }
        public int? TPFCODE9_EX { get; set; }
        public int? TPFCODE_CE { get; set; }
        public int? TPFCODE1_CE { get; set; }
        public int? TPFCODE2_CE { get; set; }
        public int? TPFCODE3_CE { get; set; }
        public int? TPFCODE4_CE { get; set; }
        public int? TPFCODE5_CE { get; set; }
        public int? TPFCODE6_CE { get; set; }
        public int? TPFCODE7_CE { get; set; }
        public int? TPFCODE8_CE { get; set; }
        public int? TPFCODE9_CE { get; set; }
        public int? TPFCODE_CT { get; set; }
        public int? TPFCODE1_CT { get; set; }
        public int? TPFCODE2_CT { get; set; }
        public int? TPFCODE3_CT { get; set; }
        public int? TPFCODE4_CT { get; set; }
        public int? TPFCODE5_CT { get; set; }
        public int? TPFCODE6_CT { get; set; }
        public int? TPFCODE7_CT { get; set; }
        public int? TPFCODE8_CT { get; set; }
        public int? TPFCODE9_CT { get; set; }
        public int? TPFCODE_DV { get; set; }
        public int? TPFCODE1_DV { get; set; }
        public int? TPFCODE2_DV { get; set; }
        public int? TPFCODE3_DV { get; set; }
        public int? TPFCODE4_DV { get; set; }
        public int? TPFCODE5_DV { get; set; }
        public int? TPFCODE6_DV { get; set; }
        public int? TPFCODE7_DV { get; set; }
        public int? TPFCODE8_DV { get; set; }
        public int? TPFCODE9_DV { get; set; }
        public int? TPFCODE_DV1 { get; set; }
        public int? TPFCODE1_DV1 { get; set; }
        public int? TPFCODE2_DV1 { get; set; }
        public int? TPFCODE3_DV1 { get; set; }
        public int? TPFCODE4_DV1 { get; set; }
        public int? TPFCODE5_DV1 { get; set; }
        public int? TPFCODE6_DV1 { get; set; }
        public int? TPFCODE7_DV1 { get; set; }
        public int? TPFCODE8_DV1 { get; set; }
        public int? TPFCODE9_DV1 { get; set; }
        public int? TPFCODE_DV2 { get; set; }
        public int? TPFCODE1_DV2 { get; set; }
        public int? TPFCODE2_DV2 { get; set; }
        public int? TPFCODE3_DV2 { get; set; }
        public int? TPFCODE4_DV2 { get; set; }
        public int? TPFCODE5_DV2 { get; set; }
        public int? TPFCODE6_DV2 { get; set; }
        public int? TPFCODE7_DV2 { get; set; }
        public int? TPFCODE8_DV2 { get; set; }
        public int? TPFCODE9_DV2 { get; set; }
        public int? TPFCODE_DV3 { get; set; }
        public int? TPFCODE1_DV3 { get; set; }
        public int? TPFCODE2_DV3 { get; set; }
        public int? TPFCODE3_DV3 { get; set; }
        public int? TPFCODE4_DV3 { get; set; }
        public int? TPFCODE5_DV3 { get; set; }
        public int? TPFCODE6_DV3 { get; set; }
        public int? TPFCODE7_DV3 { get; set; }
        public int? TPFCODE8_DV3 { get; set; }
        public int? TPFCODE9_DV3 { get; set; }
        public int? TPFCODE_DV4 { get; set; }
        public int? TPFCODE1_DV4 { get; set; }
        public int? TPFCODE2_DV4 { get; set; }
        public int? TPFCODE3_DV4 { get; set; }
        public int? TPFCODE4_DV4 { get; set; }
        public int? TPFCODE5_DV4 { get; set; }
        public int? TPFCODE6_DV4 { get; set; }
        public int? TPFCODE7_DV4 { get; set; }
        public int? TPFCODE8_DV4 { get; set; }
        public int? TPFCODE9_DV4 { get; set; }
        public int? TPFCODE_DV5 { get; set; }
        public int? TPFCODE1_DV5 { get; set; }
        public int? TPFCODE2_DV5 { get; set; }
        public int? TPFCODE3_DV5 { get; set; }
        public int? TPFCODE4_DV5 { get; set; }
        public int? TPFCODE5_DV5 { get; set; }
        public int? TPFCODE6_DV5 { get; set; }
        public int? TPFCODE7_DV5 { get; set; }
        public int? TPFCODE8_DV5 { get; set; }
        public int? TPFCODE9_DV5 { get; set; }
    }
}
