using System;
namespace PFE.Models
{
    public class ARTICLE
    {
        public int? ARTID { get; set; }
        public string ARTCODE { get; set; }
        public string ARTTYPE { get; set; }
        public string ARTISACTIF { get; set; }
        public int? AFMID { get; set; }
        public int? FRAID { get; set; }
        public int? ARUIDVENTE { get; set; }
        public int? ARTIDSUIVANT { get; set; }
        public string ARTISSUBSTITUE { get; set; }
        public int? ARTIDSUBSTITUTION { get; set; }
        public DateTime? ARTDATESUBSTITUTION { get; set; }
        public string ARTISDEFAUTFAM { get; set; }
        public string ARTDESIGNATION { get; set; }
        public string ARTDESIGNATION2 { get; set; }
        public string ARTCODEBARRE { get; set; }
        public string ARTCEECODE { get; set; }
        public string ARTCEEPRODUIT { get; set; }
        public string ARTSOUSFAMILLE { get; set; }
        public string ARTCATEGORIE { get; set; }
        public string ARTNATURE { get; set; }
        public string ARTCOLLECTION { get; set; }
        public string ARTISSTOCK { get; set; }
        public string ARTISVENDU { get; set; }
        public string ARTISFORFAIT { get; set; }
        public string ARTISSERIE { get; set; }
        public string ARTISLOT { get; set; }
        public string ARTISSTATISTIQUE { get; set; }
        public string ARTISGARANTIE { get; set; }
        public string ARTISSOUMISESC { get; set; }
        public string ARTISSOUMISCOM { get; set; }
        public string ARTISSOUMISREM { get; set; }
        public int? ARTLASTPA { get; set; }
        public int? ARTPMP { get; set; }
        public int? ARTCUMP { get; set; }
        public int? ARTSEUILVENTE { get; set; }
        public int? ARTQTEVENTEMINI { get; set; }
        public int? ARTPOIDS { get; set; }
        public int? ARTUNITEPOIDS { get; set; }
        public int? MEMOID { get; set; }
        public DateTime? DATECREATE { get; set; }
        public DateTime? DATEUPDATE { get; set; }
        public string USRMODIF { get; set; }
        public int? ARTQTEACHAT { get; set; }
        public string ARTMODESTOCK { get; set; }
        public int? ARTGARANTIE { get; set; }
        public int? NUMIDLOT { get; set; }
        public int? NUMIDSERIE { get; set; }
        public string ARTTYPENOMENCLATURE { get; set; }
        public string ARTISREPORTDES { get; set; }
        public string ARTDESCRIPTION { get; set; }
        public int? SOCID { get; set; }
        public string ARTISPERISSABLE { get; set; }
        public string ARTQTEUVISMULTI { get; set; }
        public string ARTISDIMENSION { get; set; }
        public int? DIOID { get; set; }
        public string ARTISREPORTDIM { get; set; }
        public string ARTVALOMARGE { get; set; }
        public int? ARTVOLUME { get; set; }
        public int? ARTUNITEVOLUME { get; set; }
        public int? ARTDENSITE { get; set; }
        public string ARTCONTREMARQUE { get; set; }
        public int? ARTDEEE { get; set; }
        public int? ARTPCB { get; set; }
        public string ARTPCBDESIGNATION { get; set; }
        public int? ARTLASTPR { get; set; }
        public int? ARTPRMP { get; set; }
        public int? ARTCRUMP { get; set; }
        public int? ARTTPVSENSMVT { get; set; }
        public string ARTTPVTYPEMVT { get; set; }
        public int? ARUIDSTOCK { get; set; }
        public string USRCREATE { get; set; }
        public string ARTISUSEINGP { get; set; }
        public string ARTISECOM { get; set; }
        public string ARTMARQUE { get; set; }
        public string ARTCLASSE { get; set; }
        public int? ARTLARGEUR { get; set; }
        public int? ARTLONGUEUR { get; set; }
        public int? ARTHAUTEUR { get; set; }
        public int? ARTUNITEDIM { get; set; }
        public int? ARTID_DECLINAISON { get; set; }
        public int? ARGID_1 { get; set; }
        public int? ARGID_2 { get; set; }
        public int? ARGID_3 { get; set; }
        public int? ARGVID_1 { get; set; }
        public int? ARGVID_2 { get; set; }
        public int? ARGVID_3 { get; set; }
        public int? MODID { get; set; }
    }
}
