using System;
namespace PFE.Models
{
    public class PIECEVENTE
    {
        public int PCVID { get; set; }
        public string PCVNUM { get; set; }
        public string PCVNUMEXT { get; set; }
        public string PITCODE { get; set; }
        public int? PINID { get; set; }
        public string PINCODE { get; set; }
        public int? EXEID { get; set; }
        public int? NUMID { get; set; }
        public int? AFFID { get; set; }
        public int? TRFID { get; set; }
        public int? TIRID { get; set; }
        public int? TIRID_FAC { get; set; }
        public int? TIRID_LIV { get; set; }
        public int? TIRID_REP { get; set; }
        public int? ADRID_FAC { get; set; }
        public int? ADRID_LIV { get; set; }
        public int? DEPID { get; set; }
        public int? EXPID { get; set; }
        public int? PCVCOLISAGE { get; set; }
        public int? PCVPOIDS { get; set; }
        public int? PCVUNITEPOIDS { get; set; }
        public int? JORID { get; set; }
        public int? ECRSEQUENCE { get; set; }
        public int? DEVID { get; set; }
        public int? PCVCOURSDEV { get; set; }
        public DateTime?  PCVDATEEFFET { get; set; }
        public string PCVISSOLDE { get; set; }
        public string PCVISCOMPTABILISE { get; set; }
        public string PCVISCLOS { get; set; }
        public string PCVISHT { get; set; }
        public string PCVISPRINT { get; set; }
        public int? PCVNBPRINT { get; set; }
        public DateTime?  PCVDATEPRint { get; set; }
        public int? MODID { get; set; }
        public int? PCVMNTHT { get; set; }
        public int? PCVMNTTTC { get; set; }
        public int? PCVMNTAREGLER { get; set; }
        public int? PCVMNTACOMPTE { get; set; }
        public int? PCVMNTTVA { get; set; }
        public int? PCVMNTTPF { get; set; }
        public int? PCVMNTESCOMPTE { get; set; }
        public int? PCVMNTPORT { get; set; }
        public int? PCVTAUXESCOMPTE { get; set; }
        public int? PCVCPTRELANCE { get; set; }
        public string PCVCONDREGLEMENT { get; set; }
        public string USRMODIF { get; set; }
        public DateTime?  DATEUPDATE { get; set; }
        public DateTime?  DATECREATE { get; set; }
        public int? MEMOID { get; set; }
        public int? PCVNBIMPRESSION { get; set; }
        public int? PABID { get; set; }
        public int? SOCID { get; set; }
        public string PCVISEDI { get; set; }
        public string PCVEDIETAT { get; set; }
        public DateTime?  PCVEDIDATE { get; set; }
        public string PCVEDICODELIV { get; set; }
        public DateTime?  PCVDATELIVRAISON { get; set; }
        public string PCVISDEB { get; set; }
        public string PCVDEBREGIME { get; set; }
        public string PCVDEBTRANSACTION { get; set; }
        public string PCVDEBLIVRAISON { get; set; }
        public string PCVDEBTRANSPORT { get; set; }
        public string PCVCRITREGROUPE { get; set; }
        public int? CAPID { get; set; }
        public int? PCVVOLUME { get; set; }
        public int? PCVUNITEVOLUME { get; set; }
        public string PCVISPIECEFRAIS { get; set; }
        public int? PCVREMISEPIED { get; set; }
        public int? TPVID { get; set; }
        public string TYNCODE { get; set; }
        public int? PCVNBPTSCARTE { get; set; }
        public int? ANSID { get; set; }
        public string USRCREATE { get; set; }
        public string PCVISECOM { get; set; }
        public int? PRFID { get; set; }
        public int? OXID { get; set; }
        public string PCVOBJET { get; set; }
        public int? TIRID_CPT { get; set; }
    }
}
