using System;
namespace PFE.Models
{
    public class PIECEVENTELIGNE
    {
        public int? PLVID { get; set; }
        public int? PCVID { get; set; }
        public int? PLVNUMLIGNE { get; set; }
        public string PLVTYPE { get; set; }
        public DateTime? PLVDATE { get; set; }
        public int? DEPID { get; set; }
        public int? AFFID { get; set; }
        public int? TIRIDREP { get; set; }
        public int? TIRIDFOU { get; set; }
        public int? PROID { get; set; }
        public int? ARTID { get; set; }
        public string ARTTYPE { get; set; }
        public string PLVISFORFAIT { get; set; }
        public string PLVISSOUMISESC { get; set; }
        public string PLVDESIGNATION { get; set; }
        public int? TVACODE { get; set; }
        public int? TPFCODE { get; set; }
        public int? CPTID { get; set; }
        public int? ANSID { get; set; }
        public int? PLVQTE { get; set; }
        public int? PLVQTEUS { get; set; }
        public int? PLVQTETRANSFO { get; set; }
        public int? PLVCOEFFUV { get; set; }
        public int? PLVIDORG { get; set; }
        public int? PLVPUBRUT { get; set; }
        public int? PLVPUNET { get; set; }
        public int? PLVMNTNET { get; set; }
        public int? PLVMNTNETHT { get; set; }
        public int? PLVLASTPA { get; set; }
        public int? PLVPMP { get; set; }
        public int? PLVCUMP { get; set; }
        public string PLVREMISE_F { get; set; }
        public string PLVREMISE_T { get; set; }
        public int? PLVREMISE_MNT { get; set; }
        public int? PLVSTOTID { get; set; }
        public int? PLVFRAIS1 { get; set; }
        public string PLVFRAIS1T { get; set; }
        public int? PLVFRAIS2 { get; set; }
        public string PLVFRAIS2T { get; set; }
        public int? PLVFRAIS3 { get; set; }
        public string PLVFRAIS3T { get; set; }
        public int? PLVFRAISTOTAL { get; set; }
        public int? PLVPOIDS { get; set; }
        public int? PLVUNITEPOIDS { get; set; }
        public string PLVDIVERS { get; set; }
        public string PLVCOMMENTAIRE { get; set; }
        public string PLVNUMLOT { get; set; }
        public string PLVNUMSERIE { get; set; }
        public int? PLVPUBRUTREF { get; set; }
        public string PLVARTCODE { get; set; }
        public string PLVISIMPRIMABLE { get; set; }
        public int? PVOID { get; set; }
        public string PLVSTYLEISGRAS { get; set; }
        public string PLVSTYLEISITALIC { get; set; }
        public string PLVSTYLEISIMPPARTIEL { get; set; }
        public string PLVSTYLEISSOULIGNE { get; set; }
        public int? TRFID { get; set; }
        public DateTime? PLVFEFOFABRICATION { get; set; }
        public DateTime? PLVFEFOPEREMPTION { get; set; }
        public string PLVFEFODIVERS { get; set; }
        public int? TPFCODE1 { get; set; }
        public int? TPFCODE2 { get; set; }
        public int? TPFCODE3 { get; set; }
        public int? TPFCODE4 { get; set; }
        public int? TPFCODE5 { get; set; }
        public int? TPFCODE6 { get; set; }
        public int? TPFCODE7 { get; set; }
        public int? TPFCODE8 { get; set; }
        public int? TPFCODE9 { get; set; }
        public int? PLVD1 { get; set; }
        public int? PLVD2 { get; set; }
        public int? PLVD3 { get; set; }
        public int? PLVD4 { get; set; }
        public int? PLVD5 { get; set; }
        public int? PLVD6 { get; set; }
        public int? PLVD7 { get; set; }
        public int? PLVD8 { get; set; }
        public int? PLVVOLUME { get; set; }
        public int? PLVUNITEVOLUME { get; set; }
        public int? PLVDENSITE { get; set; }
        public int? CTMID { get; set; }
        public int? PIFID { get; set; }
        public int? PLVLASTPR { get; set; }
        public int? PLVPRMP { get; set; }
        public int? PLVCRUMP { get; set; }
        public string PLVFEFODIVERS1 { get; set; }
        public string PLVFEFODIVERS2 { get; set; }
        public string PLVFEFODIVERS3 { get; set; }
        public int? PLVIDNOMC { get; set; }
        public int? PLVIDNOMCPERE { get; set; }
        public int? TCKID { get; set; }
        public string PLVISSTK { get; set; }
        public string PLVCLF { get; set; }
    }
}
